[package]
name = "dex"
version = "0.1.0"
edition = "2018"
description = "Cross-platform Pokédex."
authors = ["Teddy Byron <ted@tedbyron.com>"]
repository = "https://github.com/tedbyron/golem"
homepage = "https://github.com/tedbyron/golem"
documentation = "https://github.com/tedbyron/golem"
readme = "README.md"
license = "MIT OR Apache-2.0"
resolver = "2"

[dependencies]
iced = { features = ["image", "debug", "tokio"], git = "https://github.com/iced-rs/iced" }
rand = { version = "0.7", features = ["wasm-bindgen"] }
reqwest = { version = "0.11.4", features = ["json"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
web-sys = "=0.3.51"

[profile.dev]
debug = 0

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
